### PR TITLE
Fix false session timeout & connection error

### LINKED ISSUE #758: Alert Error server connection after login in SAML servers
### Steps to reproduce
1. In a SAML server, wait until session expires
2. Input credentials
### Expected behaviour

The session starts with no error messages 
### Actual behaviour

After input credentials, a message `It is not possible to connect to the server at this time` is always displayed
### Server configuration

{"installed":true,"maintenance":false,"version":"9.1.0.16","versionstring":"9.1.0","edition":"Enterprise"}
### Client

iPad v8.4 & v9
iPhone v9

### PR DESCRIPTION
**Pull request by davivel**
Requires owncloud/ios-library#147

Fixes owncloud/enterprise#1768
Fixes owncloud/enterprise#1775
Fixes #758

### CODE REVIEW

**Comment by jesmrec** [comment]
Connection error is already alive :(

**Comment by davivel** [comment]
> Connection error is already alive :(

Concretely, appears right after refreshing a (really) expired session.

**Comment by jesmrec** [comment]
Error message at the beginning of the session does not appear

**Comment by jesmrec** [comment]
Checked also the expiring session.

**Pull request merged**
