### PR TITLE
Download on document provider

### PR DESCRIPTION
**Pull request by ggdiez**

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Does this allow the iOS app to share files to other apps? Or does it do something else? Trying to figure out what to write about this in the development report... It'd be awesome if you could add descriptions to important pull requests :D

**Comment by MTRichards** [comment]
Basically yes, it is a sort of replacement for a filesystem since iOS doesn't have one. More info here:
http://www.imore.com/ios-8-document-provider-extensions-explained

**Comment by javiergonzper** [comment]
Exactly, thanks @MTRichards.

@jospoortvliet maybe we can ping you on the important pull request. What do you think?

**Comment by rperezb** [comment]
plus, you may join some of our demo, specially, when new features are finished

**Comment by jospoortvliet** [comment]
@javiergonzper I go over all of them anyway, if the important ones have a description or perhaps a 'big feature' tag, I'm good ;-)

**Comment by jospoortvliet** [comment]
thanks @MTRichards @rperezb I can incorporate this into the article

**Pull request merged**
