### PR TITLE
remove unnecessary comma

### PR DESCRIPTION
**Pull request by wakeup**

### CODE REVIEW

**Comment by rperezb** [comment]
Hey @wakeup thanks a lot for your pull request.

Before accepting it, we´d need you to sign the contributors agreement and send it to @karlitschek 

https://owncloud.org/contribute/agreement/

thx

**Comment by wakeup** [comment]
Hi,

I already have this agreement signed :-). do i need another one for ios?
2 Şub 2015 10:55 tarihinde "rperezb" <notifications@github.com> yazdı:

**Comment by LukasReschke** [comment]
From https://owncloud.org/contribute/agreement/:

> If you also want to contribute to the ownCloud iOS app please also send the signed "iOS Addendum" document. See the iOS license exception for testing the ownCloud iOS app on Apple hardware.

https://owncloud.org/wp-content/themes/owncloudorgnew/assets/files/Addendum_iOS.pdf

**Comment by wakeup** [comment]
Ah I see. Unfortunately I dont have a printer to print it right now. Then could you simply remove the comma after "please" from [here](https://github.com/owncloud/ios/blob/develop/Owncloud%20iOs%20Client/SupportingFiles/Languages/en.lproj/Localizable.strings#L259)

**Comment by nasli** [comment]
Thanks for your comment, we have already removed the comma.

**Pull request closed without merging**
