### PR TITLE
Migration cleanup

### PR DESCRIPTION
**Pull request by Jon-Schneider**
Pretty self-explanatory.

### CODE REVIEW

**Comment by nasli** [comment]
@Jon-Schneider looks nice! 👍

**Comment by Jon-Schneider** [comment]
Is anyone able to test this extensively? I couldn't get anything more than a few migrations back to compile. I'm most interested in testing migration from 2 and 12 because they have specialty methods besides just the migration within them.

**Comment by nasli** [comment]
@Jon-Schneider For older versions you need to compile with older versions of xcode.

**Comment by Jon-Schneider** [comment]
I got 6.6.1, the current version of Xcode at the time OwnCloud iOS 3.3.2 was current and I'm still having issues compiling 3.3.2 through 3.4. I'm pretty confident in this change but I have no way to test it. If someone has 3.3.2 or another fairly old version compiling and can test this that would be awesome, otherwise I'm afraid I'll have to close the request even though this is a desperately needed cleanup.

**Comment by nasli** [comment]
@DeepDiver1975 could you check what is wrong with the cla-bot here? Thanks!

**Comment by nasli** [comment]
@Jon-Schneider let's try to close this PR an relaunch it again into master in order to fix cla-bot, Thanks!

**Pull request closed without merging**
