### PR TITLE
[WIP] Centralized FilePreview Heading for short titles

### PR DESCRIPTION
**Pull request by raghavaro**
Fixed a problem in which the title of the file was not in the center, which looked a little odd on short headings. 

Fix https://github.com/owncloud/ios/issues/70

_____

BUGS & IMPROVEMENTS

- [ ] Set "Back" when parent folder name is longer and not misplaces the file name

### CODE REVIEW

**Comment by davivel** [comment]
@DeepDiver1975 , seems that CLA verification is not bound to the iOS repo. Could you have a look?

Thanks.

**Comment by agu3010** [comment]
**Explanation**

The titleView is placed automatically by the navigation bar, and the width of the title view was explicitly set to accommodate longer titles. But as the text was also centered in the titleView, the titleView was filling the remaining width after the back button and then it's content ie. the label was centralized.

By calling sizeToFit after setting the title, if the title is short, ie. shorter than the explicit set width, the titleView will resize itself and get centered by the navigation bar itself.

**Comment by jesmrec** [comment]
@agu3010 if the parent folder's name is a bit long, it is misplacing the filename as before happened:

screen shot 2017-03-29 at 12 01 16

maybe, it is important to take in account that depending on how long is the name of the parent folder appears either`Back`or the parent folder's name (merged in https://github.com/owncloud/ios/pull/783). What do you think @agu3010 ?

**Comment by agu3010** [comment]
@jesmrec what we can do is substitute the parent file name with the string "Back" in case it exceeds a specified length. We can also substitute the middle or trailing characters like:

Doc...567 or Docum...

A simple conditional statement can solve this. 
If you like my suggestion, I can go ahead and build this. 

For a more complex solution, we might have to rebuild the nav bar.

**Comment by jesmrec** [comment]
> what we can do is substitute the parent file name with the string "Back" in case it exceeds a specified length

imho, this is the best option so it is backwards compatible with the previous behaviour.

**Comment by jesmrec** [comment]
@agu3010 if you can fix the issue, please also rebase the branch against master ;)

**Comment by nasli** [comment]
Hi @agu3010, since you was in progress with this issue I assigned to you to keep it tracked, I hope you do not mind.

If you are having any problem with it, you can share with us.

Since no progress for last month, I assume you are no having so much free time at the moment. I am going to move to the backlog this issue. 

Feel free to unassign yourself or move it to in progress again, thanks.

**Comment by agu3010** [comment]
Hi guys, I am sorry I have been travelling for the last 2 months. I will
get back on it as soon as I can

**Comment by jesmrec** [comment]
@agu3010 we are still open to modifications here, please don't forget us! ;)

**Comment by jesmrec** [comment]
This is a bit outdated.

@raghavaro, if you still want to work on this issue, feel free to reopen.

**Comment by raghavaro** [comment]
I just started to work on the new version of the iOS app :)

**Pull request closed without merging**
