### PR TITLE
OfficeFileView: Hide top and bottom bars to maximize content view size

### LINKED ISSUE #236: As an OC iOs user I want the top and bottom bar to be half-transparent and vanish after a while so that I can focus on content
AC
-  The top and bottom bars must be half-transparent
-  The top and bottom bars must vanish after X second, if you are previewing a file
-  Once the bars have disappeared, by tapping on the file, they will be displayed again

### PR DESCRIPTION
**Pull request by legendecas**
fix #236

___

BUGS & IMPROVEMENTS:

- [x] Effect in full screen for txt files https://github.com/owncloud/ios/pull/854#issuecomment-286400220
- [x] Crash in iPad https://github.com/owncloud/ios/pull/854#issuecomment-286411119
- [x] Change orientation https://github.com/owncloud/ios/pull/854#issuecomment-286446988

### CODE REVIEW

**Comment by jesmrec** [comment]
@legendecas thank you for your contribution!! we will pass a QA stage of this PR. Please be aware it some bug or suggestion is posted here.

**Comment by jesmrec** [comment]
@legendecas 

For txt files, when are displayed in full screen and are being scrolled, the bottom bar vanishes and appears constantly, showing this effect:

mar-14-2017 12-52-08

Could it be avoided?

Device: iPhone 6 Plus 
iOS v10.1.1

**Comment by jesmrec** [comment]
Another improvable behaviour:

if you scroll up, the full screen mode is automatically disabled and both upper and bottom bars appears. 

They should appear when the user taps on the screen, not when he swipes. 

What do you think @legendecas

**Comment by legendecas** [comment]
@jesmrec For the case of do not automatically disable fullscreen mode while scrolling up, I think the time while scrolling up, it is likely that I'm going to quit or doing something else, but not focused on the text itself.

As the problem pointed out above, I would take a look and try to fix it.

**Comment by jesmrec** [comment]
@legendecas 

Feature does not work properly in iPads.

By opening a file (txt, doc, xls, ppt..) and trying to scroll it or display it in full screen, the app crashes.

**Comment by jesmrec** [comment]
Also can be improved the behaviour when the device changes orientation. Right now, the user has to tap on the screen in order to see the content full-screen if he changes orientation. Apart of that, the bottom bar is only on the right and does not occupies the whole bottom of the screen:

mar-14-2017 15-52-11

**Comment by legendecas** [comment]
@jesmrec am I supposed to squash these commits into one commit?

**Comment by jesmrec** [comment]
@legendecas we can do it after QA and code review is passed. I will check your new commits.

**Comment by jesmrec** [comment]
@legendecas the bugs are fixed, nice work!!  as you commented in https://github.com/owncloud/ios/pull/854#issuecomment-286405031, scrolling up without losing the full screen mode is not fixable. Nothing that can be done? it would be a fantastic improvement!!

**Comment by legendecas** [comment]
@jesmrec yes, it is fixable. But as I have commented that it is intended. I don't know whether everyone likes it or not, yet I do know lots of apps like YouTube, and Safari would hide something trivial when scrolling down, and show it again when scrolling up.

**Comment by jesmrec** [comment]
@legendecas ok. Then this is QA approved. Now is time for @nasli to do the code review.

**Comment by nasli** [comment]
>am I supposed to squash these commits into one commit?

@legendecas  if you wish, otherwise, please rebase the branch on master

**Comment by nasli** [comment]
Thanks for your contribution @legendecas !!

**Pull request merged**
