### PR TITLE
Release3.5.0

### LINKED ISSUE #663: [3.5.0] Release a new version
#TASKS:
- [X] [GIT] Create branch release3.5.0 (freeze the code) @mRoRo
- [X] [GIT] Create the branch release_2.0.0_library @mRoRo
- [X] [DIS] Update changelog library
- [X] [DIS] Update changelog ios app
- [X] [DEV] Update version number 3.5.0 @nasli 
- [X] [DEV] Update third party file with new library version @nasli
- [X] [DEV] Update readme library file
- [X] [DEV] Make the "3 dots" in Files view a branded element so that it could be black or white https://github.com/owncloud/ios/issues/663#issuecomment-222494341 [check if is not already brandeable]-->[Already brandeable, nothing to do]
- [X] [DEV] Refactor generate image name on instant uploads in order to use the same that the new one created for the new uploads inside the app [FIXED via  https://github.com/owncloud/ios/pull/702#discussion_r67012613] @Jon-Schneider 
- [X] [QA] Design Test plan @jesmrec
- [X] [QA] Regression Test plan @mcastroSG @jesmrec 
- [X] [DIS] Update screenshots. At least, iPad Pro ones @nasli
- [X] [DIS] Release to appstore @nasli
- [X] [GIT] Merge branch release3.5.0 @nasli
- [X] [GIT] Merge branch release_2.0.0_library @nasli
- [X] [GIT] Create tag and sign it @nasli
- [X] [DEV] Update error text when the mail is not configured  and you select to send feedback, currently: Your device doesn't support the composer sheet. -> expected: "Please, configure your mail account" [FIXED] @nasli
- [X] [DEV] Improve search users performance in share view https://github.com/owncloud/ios/issues/638#issuecomment-233329575 https://github.com/owncloud/ios/issues/663#issuecomment-235302668 @nasli 
- [X] [DEV] Add Chinese and other languages [https://github.com/owncloud/ios/issues/735] @nasli
- [X] [DEV] Add Chinese(china)" zh_CN, "Chinese (Taiwan)" zh_TW , "Albanian" sq  and "Slovenian" sl in Jenkins [@DeepDiver1975]
- [X] [DEV] Bring changes from master after changes transifex done and add Chinese new files into project, fixed Thai language @nasli
- [X] [GIT] Merge faq file with new issue https://github.com/owncloud/ios/pull/658 
- [X] [DIS] Update App Store information @nasli [updated support forum]

BRANDING CHANGES
- [X] [OB] Modify branded compilation to include and change parameters related to status bar https://github.com/owncloud/ios/issues/663#issuecomment-223055754
- [X] [OB] 3 dots icons menu [maybe not needed and already brandeable]-->[Already brandeable, nothing to do]
- [X] [OB] update HelpImage for FileDownloadedIcon (pending merge ownbrander PR after release)
- [X] [DEV] replace localized strings with the correct $appname, related PR #715 , https://github.com/owncloud/ios/issues/663#issuecomment-232424599 @mRoRo [FIXED]
- [X] "$appname" text is shown in the first help guide view. Same for "error_login_doc_provider" string https://github.com/owncloud/ios/issues/663#issuecomment-232401645 @mRoRo [FIXED]

REGRESSION BUGS FOUND:
- [X] Favorite folders are not shown as favorite in the Share Sheet https://github.com/owncloud/ios/issues/663#issuecomment-223923105 [WON'T FIX, works as expected, in the extensions this feature is not implemented since not is the scope of these view]
- [X] Uploads list cleared https://github.com/owncloud/ios/issues/663#issuecomment-230419398 @mRoRo [FIXED] 
- [X] Download files using document provider https://github.com/owncloud/ios/issues/663#issuecomment-231289776 @mRoRo [FIXED]
- [X] Video upload from the asset upload picker is broken  [FIXED via https://github.com/owncloud/ios/issues/699] @Jon-Schneider 
- [X] Uploads error after session expired https://github.com/owncloud/ios/issues/663#issuecomment-232659486 @nasli [FIXED]
- [X] "Background Instant Uploads" switch in settings tab is not enabled the first time it's enabled and the user grants permission. https://github.com/owncloud/ios/issues/663#issuecomment-233876760 [FIXED https://github.com/owncloud/ios/pull/740] @Jon-Schneider 
- [X] Instant uploads put photos on My Photo Stream Album and provokes duplicate uploads in case of two devices using the same account. https://github.com/owncloud/ios/issues/663#issuecomment-233590512 [FIXED via https://github.com/owncloud/ios/pull/718/commits/f50254008246f58f4e576c93e4d9fa90900f7a47] @Jon-Schneider 
- [X] Race condition for upload available offline files https://github.com/owncloud/ios/issues/663#issuecomment-233656327 [NOT REPRODUCEABLE]
- [X] Enable instant uploads without permissions on Photos hangs the app https://github.com/owncloud/ios/issues/663#issuecomment-234227555 [FIXED https://github.com/owncloud/ios/pull/742] @Jon-Schneider 
- [X] Crash preview files in ipad with share in server disabled  https://github.com/owncloud/ios/issues/663#issuecomment-234248716 @nasli [FIXED]
- [X] SAML sessions in iPad removes local copy of av. offline files https://github.com/owncloud/ios/issues/663#issuecomment-235304981 @nasli [FIXED]
- [X] Instant uploads of live photos duplicate photos https://github.com/owncloud/ios/issues/746 @Jon-Schneider  [FIXED] https://github.com/owncloud/ios/pull/750
- [X] SAML downloads inside folder marked as finished after a expiration https://github.com/owncloud/ios/issues/663#issuecomment-236111818 @nasli [FIXED]
- [X] SAML expiration asks always for accept certificate https://github.com/owncloud/ios/issues/663#issuecomment-236112261 [FIXED] @nasli
- [X] SAML downloads individuals with priority marked as downloading after a expiration  @nasli [FIXED] Canceled after session renewed
- [X] SAML instant uploads duplicate files and cause conflicts after expiration https://github.com/owncloud/ios/issues/663#issuecomment-238523357 [FIXED] @nasli
- [X] Login view freezes after SAML session expiration https://github.com/owncloud/ios/issues/663#issuecomment-238801664 [NO REPRODUCEABLE] 
- [X] SSO does not show authentication view https://github.com/owncloud/ios/issues/663#issuecomment-238832049 @nasli [FIXED] Added control to redirects and check if new certificates is needed in sso view
- [x] http url does not stablish connection https://github.com/owncloud/ios/issues/663#issuecomment-240712849 [FIXED] @nasli

NO REGRESSION
- [X] Upload big file in background https://github.com/owncloud/ios/issues/663#issuecomment-231995554 @nasli [FIXED]
- [X] Resumed uploads do not finish https://github.com/owncloud/ios/issues/663#issuecomment-234949111 @nasli [SERVER ISSUE, the file and folder remain locked https://github.com/owncloud/core/issues/17254#issuecomment-235336676]
- [X] SAML Session expires when the account is switched https://github.com/owncloud/ios/issues/663#issuecomment-235507410 -> https://github.com/owncloud/ios/issues/747
- [X] Av. offline folders do not start to download if they are set after SAML session expires https://github.com/owncloud/ios/issues/663#issuecomment-237787368 [WON'T FIX] @nasli Relaunched after a refresh of the file list

PR:https://github.com/owncloud/ios/pull/733

### LINKED ISSUE #735: How about appending Chinese(zh-Hans/zh-Hant) support in localization strings
### Tell us what could be improved:
There've been a large number of Chinese developers who care for owncloud. How about appending Chinese(zh-Hans/zh-Hant) support in localization strings?

### LINKED ISSUE #749: isURLWithSamlFragment hardcoded url fragments
`isURLWithSamlFragment(url)` has hardcoded strings to detect from URL if speaking to an IDP.
https://github.com/owncloud/ios/blob/master/Owncloud%20iOs%20Client/Utils/FileNameUtils.m#L258

This doesn't work out for existing infrastructures. 
Failing example:
- F5 loadbalancer, redirects (302) to location `/my.policy`, results in url like `https://sso.mycloud.com/my.policy` "Redirected to an unsecure route"

Android Client is not doing this check.

@nasli @rperezb @michaelstingl

### PR DESCRIPTION
**Pull request by mRoRo**
These closes #735, closes #663, fixes #749

### CODE REVIEW

**Comment by scolebrook** [comment]
This instance of $appname was added in https://github.com/owncloud/ios/commit/c42d7746d3702556ef9a2db762fac5f5a078d3aa. There are two more from that commit that may have exactly the same problem. files_will_be_upload_next_time and error_login_doc_provider. There probably needs to be exactly the same string substitution for all references to those strings too.

**Comment by mRoRo** [comment]
@scolebrook thanks for pointing out this. We'll fix the issue for "error_login_doc_provider". The string "files_will_be_upload_next_time" seems to be unused. 

PR al wellcome!

**Comment by nasli** [comment]
@scolebrook yes, that was introduced on purpose and was plan to fix within release branch, you can check it as a pending brandind task  here https://github.com/owncloud/ios/issues/663#issue-156213273

**Comment by scolebrook** [comment]
@mRoRo @nasli Thanks for be on top of this. I'd do a PR but I've been pulled off ownCloud at work for a week to get some other systems operational that have tight deadlines. If this is still unresolved next week when my sched starts freeing up I'll try and get something done.

**Pull request merged**
