### PR TITLE
Replace references to Favourite with "Available Offline"

### PR DESCRIPTION
**Pull request by settermjd**
As requested in owncloud/documentation/issues/2642, this PR: 

- replaces references to the outdated "_Favorites_" UI element with "_Available Offline_"

### CODE REVIEW

**Comment by nasli** [comment]
Thanks for  your PR @settermjd !
Please, review and sign the agreement

**Comment by settermjd** [comment]
@nasli - signed.

**Comment by settermjd** [comment]
@nasli I just added replaced the original image withe the Favorites button, with a new, annotated, one from the latest build, showing the available offline button, as well as updated the text. Can you give one more read through of the changes, please?

**Comment by michaelstingl** [comment]
Is this still WIP?

**Pull request merged**
