### PR TITLE
updates to user manual for 3.4.8 release

### PR DESCRIPTION
**Pull request by carlaschroder**
New screenshots, federated sharing, smaller screenies to fit better in PDFs.

### CODE REVIEW

**Comment by carlaschroder** [comment]
I am merging this after Travis is done and before OCCommunicationLib messes things up again.

**Comment by nasli** [comment]
Carla, please do not merge it, we will do it thanks!!

**Comment by carlaschroder** [comment]
ok @nasli. I don't want to fix conflicts with master again plz :)

**Comment by nasli** [comment]
Do not worry to fix conflicts, we will check it. If they are code conflict please let us fix it or help you. This is the approach we follow and prefer that other one review and merge the PR not the same person that launch it. ;)

**Comment by carlaschroder** [comment]
ok thanks @nasli

**Pull request merged**
