### PR TITLE
Fix duplicate accounts

### PR DESCRIPTION
**Pull request by nasli**
Related issue in https://github.com/owncloud/ios/issues/923

### CODE REVIEW

**Comment by jesmrec** [comment]
After checking this branch:

- Accounts are switched correctly 
- No crashes when accounts are switched 
- This bug: https://github.com/owncloud/ios/pull/919#issuecomment-334695203 happens even when the token has expired
- https://github.com/owncloud/ios/issues/923#issuecomment-347477360 is again reproducible

@nasli

**Comment by nasli** [comment]
Please @jesmrec review test 4 again, should be fixed, thanks!
For the test 3 we are going to handle in different issue since it is already in release branch

**Comment by jesmrec** [comment]
- With only one SAML account :white_check_mark:
- With two SAML accounts -> keeps happening :red_circle:
- This bug re-appears: https://github.com/owncloud/ios/issues/923#issuecomment-344854841 :red_circle:

@nasli

**Comment by nasli** [comment]
Please review again latest bugs

**Comment by jesmrec** [comment]
Updated first message with new review

**Pull request merged**
