### PR TITLE
Update connection wording

### PR DESCRIPTION
**Pull request by nasli**
Update localizable file

Secure Connection Established -> Secure Connection
Connection Established -> Non-secure connection

Fix https://github.com/owncloud/ios/issues/923#issuecomment-346008738

### CODE REVIEW

**Comment by jesmrec** [comment]
shouldn't be merged against `release_3.7.0`branch?  @nasli

**Comment by nasli** [comment]
Nope, It need to go to the master branch in order to update through transifex. 
After translations are available I will rebase in release_3.7.0
Thanks for checking it ;)

**Comment by jesmrec** [comment]
> Connection Established -> Non-secure connection

set capitals in `connection`, so we have capitals in both messages

**Comment by jesmrec** [comment]
Approved

**Comment by michaelstingl** [comment]
@CorneelDragon this will show up in Transifex soon. Could you help with the Dutch translation?

**Comment by CorneelDragon** [comment]
@michaelstingl For sure, just send me note when it's on Transifex :)

**Comment by nasli** [comment]
New strings are available @CorneelDragon

**Pull request merged**
