### PR TITLE
Create issue_template.md

### PR DESCRIPTION
**Pull request by enoch85**
Better bug reports.

You could add information about the iOS app later, I don't know what you want to I left it out.

### CODE REVIEW

**Comment by enoch85** [comment]
cc @rperezb

**Comment by rperezb** [comment]
@enoch85 what about complementing it with the info from android: https://github.com/owncloud/android/blob/reorderIssueTemplate/issue_template.md

**Comment by enoch85** [comment]
Aah, should have thought of that. Thanks! :)

**Comment by enoch85** [comment]
What about now @rperezb?

**Comment by rperezb** [comment]
thx, @enoch85 :+1: 
@owncloud/ios-developers  merge this?

**Comment by nasli** [comment]
:+1: Great! thanks for your PR!

**Pull request merged**
