### PR TITLE
Changed images in KKPasscodeLock.bundle

### PR DESCRIPTION
**Pull request by ChrisEdS**
Changed images in KKPasscodeLock.bundle

passcode

### CODE REVIEW

**Comment by michaelstingl** [comment]
like it 👍

**Comment by jesmrec** [comment]
are better a non-shadowed squares for any reason? @ChrisEdS

**Comment by ChrisEdS** [comment]
@jesmrec In my opinion it just looks cleaner and more "trustworthy" without the shadows. The old graphics are very much like 1990.

**Comment by jesmrec** [comment]
Approved for my side, 1990 is too old :D :D

**Pull request merged**
