### PR TITLE
Multi app support paths cleanup

### PR DESCRIPTION
**Pull request by Jon-Schneider**
I just sent in my contributor agreement and iOS Addendum to Carlos.

Cleans up "k_multiaccount_available" handling in several methods (all UITableViewDelegate and UITableViewDataSource methods) in SettingsViewController.m.

### CODE REVIEW

**Comment by Jon-Schneider** [comment]
I'm not sure what's up with the CI - I have all tests passing locally.

**Comment by nasli** [comment]
@Jon-Schneider travis sometimes gets stuck, I just relaunch it and all passed. Thanks for your contribution!! We'll review it and let you know.

**Comment by nasli** [comment]
@Jon-Schneider we are currently refactoring the setting view here https://github.com/owncloud/ios/tree/clear_cache_button in order to add a new clear cache feature per account, you can follow the state also here #301. 

In order you can work also on this view we are going to separate in a couple of PR, first one once we have the setting view refactored, we expect next week be ready. Then you can create your branch from this branch  and we will create also a branch from this one to continue implementing the clear cache feature.

**Comment by Jon-Schneider** [comment]
I'll plan on starting work on Instant Upload late next week then. Assuming this PR is desirable, will the changes in this PR be merged into master with clear_cache_button, or would I need to reimplement these changes after clear_cache_button is merged in next week?

**Comment by nasli** [comment]
@Jon-Schneider you can rebase your branch with "clear_cache_button" branch. Due to the refactor with same multiaccount variable I would suggest to create new PR from this branch instead of rebase it.

**Comment by Jon-Schneider** [comment]
With the changes to the 'clear_cache_button' branch I think my work changes are no longer necessary, multi-account support handling is a lot cleaner.

**Pull request closed without merging**
