### PR TITLE
Update Guide for new iOS App, new App Icon

### PR DESCRIPTION
**Pull request by hosy**
## Prepare deprecating iOS app:

To point in the "old" iOS app to the new one, we should show the user, that there exists a new app:

- changed app icon to a grayed out version, to show the user a difference to the new app (looks like disabled)
- added an update guide to point to the new iOS app and show some feature screens for the new iOS app
- Download Link will open the AppStore with the new iOS app

### Issue:
#1109

### CODE REVIEW

**Comment by jesmrec** [comment]
Approved

**Comment by hosy** [comment]
@jesmrec please can you check updating from the old app version 3.8.1 to the new version 3.8.2, because we moved the app to a new account and we had to change the app group.
I think the user need to re-enter the account credentials!?

**Comment by jesmrec** [comment]
@hosy 

i upgrade from 3.8.1 to 3.8.2 and credentials were not asked. I perform the upgrading directly with XCode. It would be useful to check with and archived ipa. Could you provide an 3.8.2 ipa to be sure?

**Comment by jesmrec** [comment]
Updating of the app is correct to 3.8.2. The only thing i detected is that the option "Discover new app" in Settings is not working fine if the touch id is enabled: if you trigger the wizard from there, and inside the wizard you click on X to dismiss (touch id asked), the wizard is not dismissed and you have to kill the app. If you tap on "Download", the appStore app is opened. If you turn back to oC (touch id asked), the wizard is there but stucked. 

With the wizard that is displayed just after upgrading, everything is correct. The bad behaviour is only with the wizard triggered from Settings.

**Comment by jesmrec** [comment]
Problem of stucked app with touch id is fixed. 

The only detail i noticed is in iPad, by triggering the wizard from the Settings section. In this case, the wizard is not displayed in full-screen, and the X is not visible in a couple of slides. 

Maybe this is not an important one and we can survive with it, since the full screen wizard when the app is upgraded is correctly displayed.

**Comment by hosy** [comment]
@jesmrec last finding for iPad also fixed

**Pull request merged**
