### PR TITLE
Populate account setup credentials from server url

### PR DESCRIPTION
**Pull request by mnutt**
If the user includes http basic credentials in their (pasted) server URL, automatically move them to the user and password fields. This streamlines setup because the user doesn't have to switch back and forth between apps to paste each value.

This PR follows https://github.com/owncloud/client/pull/4100.

This seemed to be accomplished most cleanly by using NSURLComponents to do the parsing and then reassemble the URL.

Bugs found (added for tracking)
- [X] https://github.com/owncloud/ios/issues/557
- [X] https://github.com/owncloud/ios/issues/558

### CODE REVIEW

**Comment by mnutt** [comment]
Is there anything I can do to help move this forward?

**Comment by javiergonzper** [comment]
@mnutt thanks for your pull request. We have to checkand test it before.

**Comment by mnutt** [comment]
Hi, just checking in on this. Would there be some test cases I could write to make checking it easier?

**Comment by nasli** [comment]
@mnutt Sure! You are welcome to contribute also into the OC QA repo.

From now on we are following the process detailed here:
https://github.com/owncloud/QA/blob/master/README.md
https://github.com/owncloud/QA/blob/master/Mobile/README.md 
You can find a base template for the new template here:
https://github.com/owncloud/QA/blob/master/Mobile/based_test_plan.md

To start reviewing your PR please updated with today delevop branch, some changes to the login url have been made. Thanks!

**Comment by rperezb** [comment]
@mnutt can you please update your branch with develop? So that later we may test it and merge
thanks!

**Comment by mnutt** [comment]
@rperezb I rebased it off the develop branch and it all appears to work. I attempted to follow the QA style and added a test case here: https://github.com/owncloud/QA/pull/70.

**Comment by rperezb** [comment]
@mnutt thanks! specially for following the QA style!
If you want you may complete the test plan following the one we designed for the desktop client for this feature: https://github.com/owncloud/QA/blob/Setup_Credentials/Desktop/Test_Plan_Populate_account_setup_credentials_from_server_URL.md
We will take into account this pr for our following sprint
cc @MTRichards

**Comment by jesmrec** [comment]
Hi!

Checking this feature i have found a couple of things.

First: to enable "Add" button, the connection is checked twice:

STEPS TO REPRODUCE

1.- Paste or type a URL with form "http://user:password@server:port"
2.- The user and password fields are filled up

ACTUAL BEHAVIOUR

The "Add" button keeps on disabled spite the connection is stablished. A new attempt to stablish the connection enables the button.

EXPECTED BEHAVIOUR

When the connection is stablished and user/password fields are filled, the add button gets enabled.

____

Second: The prefix "http://" or "https://" were not mandatory previously, but in this feature they are. If they are not input, the URL is not accepted but malformed. Until now, if thw prefix was omitted, the connection was too stablished (if not malformed). So, in order to keep backwards compatibility, i think the URL should be validated also without prefix.

This testings were performed with iPhone v8.4 and iPadAir v9

@mnutt: could you check them?

**Comment by mnutt** [comment]
Sure, will do. Thanks!

**Comment by jesmrec** [comment]
@mnutt first bug is fixed and closed. I hope the second one is too easy to fix :)

**Comment by jancborchardt** [comment]
@mnutt thank you for your contributions! You are also very welcome in our IRC channel #owncloud-ios (on freenode). :)

**Comment by jesmrec** [comment]
Thanks all the contributors in this pull request. Actually this funcionality is working properly.

**Comment by nasli** [comment]
@mnutt we are going to close this PR, all your code it was included in #569 with all the changes needed to pass all the test cases. Thanks for your help. You are welcome to our irc channels.

**Comment by mnutt** [comment]
It doesn't work for me, but thanks anyway.

**Comment by nasli** [comment]
@mnutt, please checkout with develop branch and tell us if you still have any issues. If so, we'd appreciate further details in order to be able to reproduce them. For us, checking different cases (https://github.com/owncloud/QA/blob/master/Mobile/iOS/Release%203.4.7/515-credentials_from_url.md) the login button is enable and the info (user id / password) are filled in automatically from the url.

Besides, if possible you may send to us a test account on your server for us to reproduce the error, please, send it to: apps@owncloud.com

**Pull request closed without merging**
