### PR TITLE
Fix fit company icon in the frame width && add sort by kind

### LINKED ISSUE #868: App icon in iPads does not fit the screen width
In iPads, the app icon does not fit with the frame width:

a6280434-7e6f-11e6-8d3c-f85df20f918b

### LINKED ISSUE #944: Sorting on 'kind' like Mac OS
Hi there,

A colleague of mine (William van Santen from SURF) spoke on the ownCloud Conference last week with app development about sorting of files on kind and was asked to make an issue. 

Now you can sort on date and alphabet, which is great. However, on Mac OS you also have the option to sort on 'kind'. This allows you to not only quickly find files based on their extension, but it also could 'fix' this request: https://github.com/owncloud/ios/issues/481. Since Mac automatically put folders on top when sorting on 'kind' is selected. 

Let me know what you think!

### PR DESCRIPTION
**Pull request by MathPlayer**
I added constraints for some space on all side of the image (16px) as well as preserving the image ratio.

--- Updated
- [x] Fix #868  fit company icon in the frame width [FIXED]
- [x] Fix #944 Enable sort by kind

### CODE REVIEW

**Comment by MathPlayer** [comment]
I have in my master branch another issue fixed and I don't know if it's alright with you to merge both changes from this pull request or to create another branch for the second change and open a pull request.
I'll wait for your guidance on this (e.g. how to create at the same time two pull requests for two different issues)

**Comment by nasli** [comment]
Thank you for your contribution @MathPlayer !
In this case is ok, their are tiny and you have already done de pr. 
For future PRs, yes just launch one PR per feature or fix.

In order to be clear what this PR include I will update your first comment.

**Comment by nasli** [comment]
>how to create at the same time two pull requests for two different issues

@MathPlayer you can create a different branches from master, one per feature or fix, and launch each branch as new PR.

If you need more help reply. I will move to QA this PR. Thanks!

**Comment by jesmrec** [comment]
thanks for your contribution @MathPlayer.

- The icon in iPads fits correctly. Fixed
- Regarding sorting by kind, i detected that a orientation change in the device makes a sorting by kind, whatever the sorting previous set. Could you have a look?

**Comment by MathPlayer** [comment]
I will look into this. Funny thing is I reproduced it the first time after I saw your comment, but no more after that. Can you describe a bit more the actions you're doing?

**Comment by jesmrec** [comment]
1. Attach an account to the app, by default is sorted by A-Z
2. Sort by "Newest-Oldest"
3. Change device orientation to landscape

From this point, any orientation change will sort the list by kind.

**Comment by MathPlayer** [comment]
When changing orientation, the sorting sheet was dismissed with a hard-coded value for cancel. When I added a new button, that transform into "always sort by kind". A fix for this problem is in fea0280

**Pull request merged**
